### ISSUE TITLE
explane

### ISSUE THREAD

**Issue by yokosta** [purplesmoke05/solana-arb#1]
HI. How to run your soft? What is the configuration file? I will be glad to explain, unexplain. Sorry I did not find your discord or other ways to you. thank you

**Comment by purplesmoke05** [comment]
Thanks for your message.

This repository is now on WIP.
I will add instructions on how to use it and how to set it up soon.

**Comment by yokosta** [comment]
Hi. I appreciate your response. How's it going, what worked and what didn't? Good luck, I hope you found a code that makes it possible to implement your idea.
